title: "T-Mania"
description: "T-Mania Open-Air Festival"

locale: "de-DE"
remote_theme: "mmistakes/minimal-mistakes"
url: "http://t-mania.de"

logo: /assets/images/t-mania-logo.png


paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

# Collections
collections:
  aktuelles:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _aktuelles
  - scope:
      path: ""
      type: aktuelles
    values:
      layout: single
      author_profile: false
      read_time: false
      share: false
      comment: false
      related: false

footer:
  links:
    - label: "Faceboook"
      icon: "fab fa-facebook-f"
      url: "https://www.facebook.com/tmania.openair/"
    - label: "YouTube"
      url: "https://www.youtube.com/user/tittemania/videos"
      icon: "fab fa-youtube"    
    - label: "Shop"
      url: "https://t-mania.myspreadshop.de"
      icon: "fab shopping-cart"
    - label: "Impressum"
      url: "/impressum"
      icon: "fab paragraph"
    - label: "Datenschutz"
      url: "/datenschutz"
      icon: "fab shield"