title: "T-Mania"
# title: "VERMUKU"
description: "T-Mania Open-Air Festival"

locale: "de-DE"
remote_theme: "mmistakes/minimal-mistakes"
url: "http://monaboeker.de"
# baseurl: "/tboeker"
# repository: "tboeker/vermuku.de"

logo: /assets/images/t-mania-logo.jpg

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
